### ISSUE TITLE
[EPIC][DevOps] Automation to provision Harvester integrations in both "airgap" & "non-airgap" ecosystems

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#1101]
## Problem
- Harvester integrations are primarily provisioned manually 

## Automation Possibility 
- Leaning in to leveraging Harvester to run our "Harvester" integrations, this could be implemented in either:
    - bare-metal-container workloads with corresponding deployments in k8s
    - vm(s) supporting the underlying integrations provisioned
- Integrations being re-provisioned via elements like:
    - cron based
    - GitOps based
    - trigger based via actor
 - Provisioning being conducted via centralized Jenkins

## Automation Items
- [ ] `Elasticsearch (supports rancher-logging addon)`
- [ ] `Kibana (supports rancher-logging addon)`
- [ ] `MinIO (supports backup)`
- [ ] `NFS (supports backup)`
- [ ] `Docker-Registry / Image Registry (supports providing centralized location for images)`
- [ ] `DNS (supports host location support in airgapped/non-airgapped)`
- [ ] `NTP (supports airgapped clusters)`
- [x] `OpenStack (supports vm-import addon)`
- [ ] `Configured Alertmanager Loadout (supports rancher-monitoring addon)`
- [ ] `Harvester Fleet Support (supports Fleet via something like self-hosted GitLab)`
- [ ] `iSCSI Server (supports storage integrations)`

**Comment by irishgordo** [comment]
This is still a WIP.

OpenStack has been accomplished via:
- https://github.com/harvester/harvester-baremetal-ansible/tree/master/terraform/integrations/openstack
