### ISSUE TITLE
[TEST] Set up Cypress test to run on bare-metal in the lab for CI

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1697]
## What's the test to develop? Please describe

Like e2e test we should use seeder to provision Harvester cluster on Bare-metal in the lab and run cypress test on it.

- [ ] Add GitHub workflow to trigger Cypress e2e tests on PRs and merges. Repo - https://github.com/harvester/harvester-ui-extension
- [ ] Add a runner in Harvester lab (VM is OK) and the runner provisions seeder clusters and runs UI tests.

**Comment by khushboo-rancher** [comment]
cc: @bk201

**Comment by albinsun** [comment]
## Phase
### Survey
- [ ] Prepare a document includes @TachunLin 
  * Build a test env. from scratch
  * Trigger test (Jenkins job result)
  * Gen and check report (MinIO Link)
- [ ] Survey Github action runner @albinsun 
- [ ] Fix Lab Cypress (Pipeline and MinIO...) @TachunLin @albinsun 

### ToDo
- [ ] Refactor cypress testing to conform CI flow @albinsun 
- [ ] TBD

**Comment by TachunLin** [comment]
I create a simple CI flow chart for the Cypress test and Harvester dashboard (ui-extension) integration.

This may provide the development scope to complete this task from create PR to trigger the action -> build the required artifact files -> build test environment -> run cypress test -> Judgement then merge. 

  ![image](https://github.com/user-attachments/assets/a744748a-de9f-4445-9641-7a639bacfdc8)

I marked these stage with number to help with our discussion for which stage of component we already have. 
What's it's current status, how should we implement and finally integrate them to become the workflow. 

Update the current state of Cypress test pipeline status: 
* For stage 4, the cypress pipeline test environment was built upon the vm on the specific bare-metal machine
  - Thus I marked the `VM` option to green for what we already used 
  - We can also consider using entire bare-metal seeder machine, we should need to create some new pipelines to handle. 
* For stage 5, we use Jenkins cypress test pipeline as the runner to trigger the cypress test suite. 
  - Thus I marked the `Jenkins` option to green 
  - We can also consider using the `Github action` only, but we need to have extra effort to design and transfer tasks performed in Jenkins

This is my initial idea in my and update the current Cypress status. 
I may not have a very clear understanding of the entire process and miss something.

Just feel free to comment and share with more information and join the discussion. Many thanks.  :smiley:
cc: @bk201, @torchiaf, @a110605

**Comment by a110605** [comment]
> This is my initial idea in my and update the current Cypress status. I may not have a very clear understanding of the entire process and miss something.
> 
> Just feel free to comment and share with more information and join the discussion. Many thanks. 😃 cc: @bk201, @torchiaf, @a110605

Thanks @TachunLin's flow picture, I want to point out in stage 4 if we build the whole harvester deployment from scratch, it will take too long to have e2e tests result. It doesn't make sense to wait for 1 hr for each PR created / update to wait for e2e test result.

We might consider using an existing harvester deployment (do VM clone ?) to quickly get harvester test env.

**Comment by albinsun** [comment]
Per discussed, close this ticket and translate to following ones:
1. https://github.com/harvester/tests/issues/1692
   * PR: https://github.com/harvester/harvester-baremetal-ansible/pull/90
2. https://github.com/harvester/tests/issues/1726
   * https://github.com/harvester/harvester-baremetal-ansible/pull/92
   * https://github.com/harvester/harvester-baremetal-ansible/pull/93

Let's create a new ticket if require similiar feature in the future.

cc. @TachunLin @a110605 @bk201 @khushboo-rancher
