### ISSUE TITLE
[TEST] Enable cypress Jenkins Job for daily-run and support different branches 

### ISSUE THREAD

**Issue by albinsun** [harvester/tests#1726]
## What's the test to develop? Please describe
We want _harvester-cypress-*_ Jenkins jobs supports:
1. Daily run
2. Test on different branches

### Phase 1
- [x] Setup a new cypress testbed (For not to affect the production one).
- [x] On staging Jenkins, can successfully run _harvester-cypress-test_.
- [x] Enable daily test on public branched (`master` and `v1.4` ...)
- [x] Send phase 1 PR
    * harvester/harvester-baremetal-ansible/pull/92
### Phase 2
- [x] Add field to test _harvester-ui-extension_ to test private build
- [x] Send phase 2 PR
   * harvester/harvester-baremetal-ansible/pull/93

## Additional context
n/a

**Comment by albinsun** [comment]
* Setup a new cypress testbed (For not to affect the production one).
* Can successfully run harvester-cypress-test and harvester-cypress-run-test.
![image](https://github.com/user-attachments/assets/c3360237-35b1-4db6-8a64-c0f3f30ac053)

**Comment by albinsun** [comment]
* Can test different branches daily 
![Image](https://github.com/user-attachments/assets/241c642a-a52d-43d4-a3d7-e893264c5415)

**Comment by albinsun** [comment]
## Phase 2
Config `ui-index` and `ui-source` by Harvester Configuration

### v1.4-rc1
* `harvester_ui_index`: EMPTY
  ![Image](https://github.com/user-attachments/assets/865bfdc8-f0f2-4262-bd23-ff92d2489c53)

* Result: `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.4/index.html`
  ![Image](https://github.com/user-attachments/assets/533b7a9f-33c0-4af8-b3f9-48a748540e53)

* Report
  ![Image](https://github.com/user-attachments/assets/460f7488-fff5-41a7-bbd7-38a63254313d)


### v1.4-rc1 + Harvester Configuration
* `harvester_ui_index`: `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
  ![Image](https://github.com/user-attachments/assets/86013b31-2feb-48d6-8b2a-0a2652373654)

* Result: `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
  ![Image](https://github.com/user-attachments/assets/d5c9a962-2273-4478-be3c-334b2a36442d)

* Report
  ![Image](https://github.com/user-attachments/assets/bd05d772-4ace-4d28-a1c9-ac03f3d59777)
