### ISSUE TITLE
[TASK] Create frontend Cypress test script for Rancher integration 

### ISSUE THREAD

**Issue by TachunLin** [harvester/tests#471]
### Task Requirement
Develop Cypress frontend test script for Rancher integration

### Environment
- Rancher v2.6.7
- Harvester v1.0.3 
- Cypress: 10.2 

### Task
- [x] Prepare Harvester Image
- [x] Prepare Harvester VLAN network
- [x] Bootstrap Rancher and set password
- [x] Normal Rancher login 
- [x] Rancher import Harvester
- [x] Harvester import Rancher
- [x] Check Harvester Cluster Status
- [x] Create cloud credential
- [ ] Create RKE1 node template
- [ ] Provisiong RKE1 cluster
- [x] Provisiong RKE2 cluster
- [x] Provisiong K3s cluster
- [ ] Check RKE1 cluster Status
- [x] Check RKE2 cluster Status
- [x] Check K3s cluster Status
- [x] Verify RKE2 CSI driver
- [x] Verify RKE2 cloud provider
- [x] Verify RKE2 DHDP Load Balancer
- [x] Verify RKE2 Pool Load Balancer
- [ ] Install and verify RKE1 CSI driver
- [ ] Install and verify RKE1 cloud provider 
- [ ] Install and verify K3s CSI driver
- [ ] Install and verify K3s cloud provider
- [ ] Delete RKE1 cluster
- [x] Delete RKE2 cluster
- [x] Delete K3s cluster
- [ ] Delete RKE1 node template
- [x] Delete cloud credential 
- [x] Delete Imported Harvester

**Comment by TachunLin** [comment]
* A regular test suite flow looks like the following
![image](https://user-images.githubusercontent.com/29251855/187932316-23a38e5a-c893-40ed-8901-91a3531bf238.png)

**Comment by TachunLin** [comment]
Commit the Initial release on https://github.com/harvester/tests/pull/502

**Comment by TachunLin** [comment]
Currently the RKE1 node template running on cypress runner encounter blank page 
  ![image](https://user-images.githubusercontent.com/29251855/189099263-1371f9de-e586-4e24-83a8-c39b28e0d551.png)

It may required adding `modifyObstructiveCode: false` in cypress.config.ts
https://github.com/cypress-io/cypress/issues/9614 

Plan to check this solution again after https://github.com/cypress-io/cypress/pull/23694 applied to latest Cypress.

**Comment by TachunLin** [comment]
Hi @asc5543, 

The Rancher integration test have been covered by e2e test. 
We probably won't have plan to implement this part of cypress script in the near future. 
Thus I would suggest to close it as not planned. 
If need. I will create a new test issue to restart this task. Thank you.

**Comment by asc5543** [comment]
Thanks the confirmation of @TachunLin .
Close this test issue.
