### ISSUE TITLE
[TASK] Setup PXE boot installation for Home lab Harvester cluster 

### ISSUE THREAD

**Issue by TachunLin** [harvester/tests#587]
### Task Requirement
In the past, I use ISO installation to provision the four nodes Harvester cluster on home lab tower machine. 
In order to provide the availability of using Harvester configuration file on PXE boot installation.  
This would provide more options and an suitable bare metal environment to test the vlan related test on multiple NICs.

### Task List 
- [x] Prepare and config the PXE server 
- [x] Setup HTTP server
- [x] Setup DHCP server
- [x] Setup tftp server
- [x] Prepare the DHCP configuration file 
- [x] Prepare Installation installation boot image files
- [x] Prepare and test Harvester configuration file for create mode (config-create.yaml)
- [x] Prepare and test Harvester configuration file for join mode (config-join.yaml)
- [x] Prepare ipxe script ipex-create (create mode)
- [x] ipxe script ipex-join (join mode)
- [x] Adjust to use fixed VIP, four nodes IPs on DHCP
- [x] Test can provision node 1 machine in create mode 
- [x] Test can provision node 2 machine in join mode 
- [x] Test can provision node 3 machine in join mode
- [x] Test can provision node 4 machine in join mode

**Comment by TachunLin** [comment]
Now can successfully provision 4 nodes cluster on tower bare metal machines using PXE boot installation with on-demand Harvester configuration files. 

![image](https://user-images.githubusercontent.com/29251855/199401002-714a4355-a086-482e-820d-993747f55b3c.png)


Close this task.
