### ISSUE TITLE
[TASK] Measure the execution time of current Cypress test suites

### ISSUE THREAD

**Issue by TachunLin** [harvester/tests#595]
### Task Requirement
Measure the total execution time of existing Cypress test suite on 
https://github.com/harvester/tests/tree/main/cypress 

We can use this execution time information to evaluate how long it will take to run Cypress test on internal daily Jenkins server 

### Test suites List

- [ ] 1. VM settings
- [ ] 2. backups
- [ ] 3. dashboard
- [x] 4. image -> 6 minutes 13 seconds
- [ ] 5. namespaces
- [x] 6. networks -> 1 minutes 6 seconds
- [x] 7. settings -> 1 minutes 6 seconds
- [ ] 8. templates
- [ ] 9. virtualmachines
- [x] 10. volume -> 3 minutes 15 seconds

### Plan
1. Measure each test suite execution
2. Calculate the total execution time

**Comment by TachunLin** [comment]
According to the testing on PR [331](https://github.com/harvester/tests/pull/331/) 
with Harvester `v1.1.0` 

* All **image** test takes 6 minutes 13 seconds execution time - 193 seconds

![image](https://user-images.githubusercontent.com/29251855/200287056-b576fd63-32ea-4bff-99c4-c47faf552d75.png)

**Comment by khushboo-rancher** [comment]
Closing this, if require feel free to reopen it.
