### ISSUE TITLE
[Epic] v1.1.2 e2e test cases

### ISSUE THREAD

**Issue by WuJun2016** [harvester/tests#606]
#### Volume
- [x] https://harvester.github.io/tests/manual/volumes/support-volume-hot-unplug/ @DaiYuzeng
- [x] https://harvester.github.io/tests/manual/volumes/edit-volume-increase-size-form/ @DaiYuzeng
- [x] https://harvester.github.io/tests/manual/volumes/detach-volume-from-virtual-machine/ @DaiYuzeng

### Virtual Machine
- [x] https://harvester.github.io/tests/manual/virtual-machines/edit-vm-and-insert-ssh-and-check-the-ssh-key-is-accepted-for-the-login/    @n313893254 
- [x] https://harvester.github.io/tests/manual/virtual-machines/edit-a-vm-from-the-form-to-add-user-data/   @n313893254 
- [x] https://harvester.github.io/tests/manual/virtual-machines/1602-delete-vm-with-exported-image/   @n313893254 
- [x] https://harvester.github.io/tests/manual/virtual-machines/create-vm-with-existing-volume/  @WuJun2016 
- [x] https://harvester.github.io/tests/manual/virtual-machines/create-vm-using-a-template-non-default-version/   @n313893254 
- [x] https://harvester.github.io/tests/manual/virtual-machines/create-multiple-instances-vm-with-raw-image/  @n313893254 
- [x] https://harvester.github.io/tests/manual/virtual-machines/create-a-new-vm-with-network-data-from-the-form/  @n313893254 
- [x] https://harvester.github.io/tests/manual/virtual-machines/clone-vm-that-was-created-from-image/   @WuJun2016  
- [x] https://harvester.github.io/tests/manual/virtual-machines/clone-vm-existing-volume/  @WuJun2016  
~- [ ] https://harvester.github.io/tests/manual/virtual-machines/clone-vm-and-dont-select-start-after-creation/  @WuJun2016~
- [x] https://harvester.github.io/tests/manual/virtual-machines/1283-vm-creation-required-fields/   @WuJun2016  
- [ ] https://harvester.github.io/tests/manual/templates/allow-users-to-create-cloud-config-template-on-vm-creating-page/  @DaiYuzeng 
- [x] https://harvester.github.io/tests/manual/_incoming/2376-2379-delete-vm-template-default-version/  @DaiYuzeng 

### Image
- [x] https://harvester.github.io/tests/manual/_incoming/2562-clone-image/  @DaiYuzeng 
- [x] https://harvester.github.io/tests/manual/_incoming/2563-image-naming-inline-css/  @DaiYuzeng 
- [x] https://harvester.github.io/tests/manual/_incoming/2474-image-filtering-by-labels/  @DaiYuzeng 

### Dashboard
- [x] https://harvester.github.io/tests/manual/authentication/logout-then-login/  @WuJun2016  

### Volume
- [x] https://harvester.github.io/tests/manual/volumes/delete-volume-that-was-attached-to-vm-but-is-not-now/ @DaiYuzeng 

### VM
- [x] https://harvester.github.io/tests/manual/virtual-machines/negative-stop-vm/ @n313893254 
- [x] https://harvester.github.io/tests/manual/_incoming/2577-template-with-efi/  @n313893254 
- [x] https://harvester.github.io/tests/manual/_incoming/2578-all-namespace-filtering/  @WuJun2016 

### nav
- [x] https://harvester.github.io/tests/manual/ui/verify-url/ @WuJun2016 

## p2
~- [ ] https://harvester.github.io/tests/manual/images/negative-upload-invalid-image-file/ @WuJun2016~   
- [x] https://harvester.github.io/tests/manual/authentication/1409-change-password/ @DaiYuzeng  
- [x] https://harvester.github.io/tests/manual/advanced/set-s3-backup-target/  @DaiYuzeng 
- [x] https://harvester.github.io/tests/manual/virtual-machines/vm_schedule_on_node/ @DaiYuzeng 
- [x] https://harvester.github.io/tests/manual/_incoming/2294_support_volume_snapshot/ @WuJun2016 
- [x] https://harvester.github.io/tests/manual/_incoming/3004-volume-snaphost-not-include-vm/  @WuJun2016 
- [x] https://harvester.github.io/tests/manual/_incoming/553_vm_snapshot_support/ @WuJun2016 
- [x] https://harvester.github.io/tests/manual/_incoming/2296_volumesnapshot_management/ @WuJun2016 
- [x] https://harvester.github.io/tests/manual/backup-and-restore/backup-single-vm/ @WuJun2016 
- [x] https://harvester.github.io/tests/manual/backup-and-restore/restore-backup-create-new-vm/
- [x] https://harvester.github.io/tests/manual/backup-and-restore/restore-backup-create-new-vm-in-another-namespace/ @WuJun2016 
- [x] https://harvester.github.io/tests/manual/backup-and-restore/delete-single-backup/ @WuJun2016

**Comment by DaiYuzeng** [comment]
https://harvester.github.io/tests/manual/volumes/support-volume-hot-unplug/
https://harvester.github.io/tests/manual/volumes/detach-volume-from-virtual-machine/
https://harvester.github.io/tests/manual/volumes/edit-volume-increase-size-form/

I will work on above issues at first @WuJun2016 @DaiYuzeng

**Comment by khushboo-rancher** [comment]
Closing as all the tasks mentioned marked completed. @WuJun2016 Feel free to reopen if anything is left to complete.
