### ISSUE TITLE
[TASK] Add initial upgrade manual test plan 

### ISSUE THREAD

**Issue by TachunLin** [harvester/tests#609]
### Requirement
Start with the v1.1.1 regression test, we need add a Harvester upgrade category 
Create a new upgrade folder and add some upgrade related test plans in https://github.com/harvester/tests/pull/607 

### Task List
Test plan including: 

- [ ] Upgrade with IPv6 network
- [ ] Upgrade from v1.0.3 to v1.1.1
- [ ] Upgrade from v1.1.0 to v1.1.1
- [ ] Fully air-gapped upgrade
- [ ] Rejoin node after upgrade
- [ ] Upgrade from cluster network on bonded NICs

**Comment by khushboo-rancher** [comment]
This is Done.
